"""Phase 2 (ML): compile the DAG to a SageMaker Pipelines SDK definition.

Emits, at the ZIP root:
- pipeline/pipeline.py      — assembles a sagemaker.workflow.pipeline.Pipeline
- pipeline/run.py           — `pipeline.upsert(role_arn=...)` + `.start()`
- pipeline/__init__.py
"""
from __future__ import annotations

import textwrap

from ..._types import CompiledArtifacts, CompiledFile
from ...models.graph import Node, Project


def compile_ml_pipeline(project: Project, sorted_nodes: list[Node]) -> CompiledArtifacts:
    artifacts = CompiledArtifacts()
    pipeline_name = _name(project.name)
    artifacts.add(CompiledFile(path="pipeline/__init__.py", content=""))
    artifacts.add(_gen_pipeline_py(project, sorted_nodes, pipeline_name))
    artifacts.add(_gen_run_py(pipeline_name))
    return artifacts


def _name(raw: str) -> str:
    return raw.lower().replace(" ", "-").replace("_", "-")


def _py_id(node_id: str) -> str:
    """Sanitized identifier for use as a Python variable name."""
    return node_id.replace("-", "_").replace(" ", "_")


def _gen_pipeline_py(
    project: Project,
    sorted_nodes: list[Node],
    pipeline_name: str,
) -> CompiledFile:
    node_map = {n.id: n for n in project.nodes}
    predecessors: dict[str, list[str]] = {n.id: [] for n in project.nodes}
    for e in project.edges:
        if e.target_node_id in predecessors and e.source_node_id in node_map:
            predecessors[e.target_node_id].append(e.source_node_id)

    skip_step_types = {"input", "output", "condition", "human_in_the_loop",
                       "data_source_s3", "endpoint_realtime"}

    body_blocks: list[str] = []
    step_vars: list[str] = []
    for n in sorted_nodes:
        if n.type in skip_step_types:
            continue
        pred_nodes = [node_map[pid] for pid in predecessors.get(n.id, [])]
        depends = [
            f"step_{_py_id(p.id)}"
            for p in pred_nodes
            if p.type not in skip_step_types
        ]
        depends_arg = f", depends_on=[{', '.join(depends)}]" if depends else ""
        block = _emit_step(n, pred_nodes, depends_arg)
        if block:
            body_blocks.append(block)
            step_vars.append(f"step_{_py_id(n.id)}")

    body = "\n\n".join(body_blocks) if body_blocks else "# (no steps generated — empty graph)"
    steps_list = ", ".join(step_vars) if step_vars else ""

    content = f'''\
"""SageMaker Pipelines definition for {pipeline_name}.

Generated by the JaguarData ML Studio. Import `pipeline` and call
`pipeline.upsert(role_arn=...)` to register/update it in SageMaker, then
`pipeline.start()` to launch an execution. See pipeline/run.py for the
full deploy + run cycle, and deploy-sagemaker.ipynb for the notebook flow.
"""
from __future__ import annotations

import os

from sagemaker.workflow.pipeline import Pipeline
from sagemaker.workflow.steps import ProcessingStep, TrainingStep
from sagemaker.workflow.step_collections import RegisterModel
from sagemaker.workflow.parameters import ParameterString
from sagemaker.processing import ProcessingInput, ProcessingOutput, Processor
from sagemaker.estimator import Estimator
from sagemaker.inputs import TrainingInput

PIPELINE_NAME = "{pipeline_name}"
REGION = os.environ.get("AWS_REGION", "us-east-1")
ROLE_ARN = os.environ.get("SAGEMAKER_ROLE_ARN", "")
DEFAULT_BUCKET = os.environ.get("SAGEMAKER_DEFAULT_BUCKET", "")

# Pipeline parameters — override at execution time via pipeline.start(parameters={{...}}).
param_input_s3 = ParameterString(name="InputS3Uri", default_value="")


{body}


pipeline = Pipeline(
    name=PIPELINE_NAME,
    parameters=[param_input_s3],
    steps=[{steps_list}],
)
'''
    return CompiledFile(path="pipeline/pipeline.py", content=content)


def _emit_step(n: Node, predecessors: list[Node], depends_arg: str) -> str:
    """Returns the Python source for one step, or '' when the node has no step."""
    step_var = f"step_{_py_id(n.id)}"
    cfg = n.config
    first_pred = predecessors[0] if predecessors else None

    if n.type == "processing_job":
        name = cfg.get("name", n.id)
        image_uri = cfg.get("image_uri", "")
        instance_type = cfg.get("instance_type", "ml.m5.large")
        instance_count = cfg.get("instance_count", 1)
        script_uri = cfg.get("script_uri", "")
        output_s3 = cfg.get("output_s3_uri", "")

        if first_pred and first_pred.type == "data_source_s3":
            input_src = f'"{first_pred.config.get("s3_uri", "")}"'
        else:
            input_src = "param_input_s3"

        return textwrap.dedent(f'''\
            # ── Processing step: {name} ─────────────────────────────────────
            _processor_{_py_id(n.id)} = Processor(
                image_uri="{image_uri}",
                role=ROLE_ARN,
                instance_count={instance_count},
                instance_type="{instance_type}",
                base_job_name="{name}",
            )
            {step_var} = ProcessingStep(
                name="{name}",
                processor=_processor_{_py_id(n.id)},
                inputs=[ProcessingInput(source={input_src}, destination="/opt/ml/processing/input")],
                outputs=[ProcessingOutput(source="/opt/ml/processing/output", destination="{output_s3}")],
                code="{script_uri}"{depends_arg},
            )''')

    if n.type == "training_job":
        name = cfg.get("name", n.id)
        image_uri = cfg.get("image_uri", "")
        instance_type = cfg.get("instance_type", "ml.m5.large")
        instance_count = cfg.get("instance_count", 1)
        output_s3 = cfg.get("output_s3_uri", "")
        hyperparams = cfg.get("hyperparameters", {}) or {}
        hyperparams_repr = repr(hyperparams)

        if first_pred and first_pred.type == "processing_job":
            input_data = (
                f'step_{_py_id(first_pred.id)}.properties.'
                f'ProcessingOutputConfig.Outputs["output"].S3Output.S3Uri'
            )
        elif first_pred and first_pred.type == "data_source_s3":
            input_data = f'"{first_pred.config.get("s3_uri", "")}"'
        else:
            input_data = "param_input_s3"

        return textwrap.dedent(f'''\
            # ── Training step: {name} ───────────────────────────────────────
            _estimator_{_py_id(n.id)} = Estimator(
                image_uri="{image_uri}",
                role=ROLE_ARN,
                instance_count={instance_count},
                instance_type="{instance_type}",
                output_path="{output_s3}",
                base_job_name="{name}",
                hyperparameters={hyperparams_repr},
            )
            {step_var} = TrainingStep(
                name="{name}",
                estimator=_estimator_{_py_id(n.id)},
                inputs={{"train": TrainingInput(s3_data={input_data})}}{depends_arg},
            )''')

    if n.type == "model_register":
        group = cfg.get("model_package_group_name", n.id)
        approval = cfg.get("approval_status", "PendingManualApproval")
        content_types = cfg.get("content_types", ["application/json"])
        response_types = cfg.get("response_types", ["application/json"])
        inference_instances = cfg.get("inference_instances", ["ml.m5.large"])

        # Source the model from the upstream training job's outputs.
        if first_pred and first_pred.type == "training_job":
            estimator_var = f"_estimator_{_py_id(first_pred.id)}"
            model_data = (
                f"step_{_py_id(first_pred.id)}.properties."
                f"ModelArtifacts.S3ModelArtifacts"
            )
        else:
            estimator_var = "None"
            model_data = '""'

        return textwrap.dedent(f'''\
            # ── Register model step ─────────────────────────────────────────
            {step_var} = RegisterModel(
                name="register-{group}",
                estimator={estimator_var},
                model_data={model_data},
                model_package_group_name="{group}",
                approval_status="{approval}",
                content_types={content_types!r},
                response_types={response_types!r},
                inference_instances={inference_instances!r},
                transform_instances=["ml.m5.large"]{depends_arg},
            )''')

    return ""


def _gen_run_py(pipeline_name: str) -> CompiledFile:
    content = f'''\
"""Run script — upserts and starts the SageMaker Pipeline.

Usage:
    SAGEMAKER_ROLE_ARN=arn:aws:iam::...:role/{pipeline_name}-sagemaker \\
    SAGEMAKER_DEFAULT_BUCKET=my-bucket \\
    python -m pipeline.run --input-s3 s3://my-bucket/input/
"""
from __future__ import annotations

import argparse
import os

from pipeline.pipeline import pipeline


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-s3", default="")
    parser.add_argument("--wait", action="store_true", help="Block until execution completes")
    args = parser.parse_args()

    role_arn = os.environ.get("SAGEMAKER_ROLE_ARN", "")
    if not role_arn:
        raise SystemExit("Set SAGEMAKER_ROLE_ARN before running.")

    pipeline.upsert(role_arn=role_arn)
    print(f"Pipeline '{{pipeline.name}}' upserted in SageMaker.")

    parameters = {{"InputS3Uri": args.input_s3}} if args.input_s3 else {{}}
    execution = pipeline.start(parameters=parameters)
    print(f"Execution started: {{execution.arn}}")

    if args.wait:
        execution.wait()
        print(f"Execution finished. Status: {{execution.describe()['PipelineExecutionStatus']}}")


if __name__ == "__main__":
    main()
'''
    return CompiledFile(path="pipeline/run.py", content=content)
